image: Visual Studio 2017

version: configuring.{build}
configuration:
- Debug

environment:
  VSTOOLSET: v141


platform:
- x64

clone_folder: c:\cabbage

# scripts that run after cloning repository
install:
  - cmd: dir  
  - cmd: cd c:/
  - ps: Start-FileDownload 'https://github.com/csound/csound/releases/download/6.11.0/csound-windows_x64-6.11.0.zip'
  - cmd: 7z.exe x csound-windows_x64-6.11.0.zip -o"C:/Program Files"
  - cmd: cd "C:/Program Files/Csound6_x64"
  - cmd: dir
  # - cmd: mkdir "C:/Program Files/Csound6_x64"
  # - ps: Get-ChildItem -Path "C:/Csound6_x64" | Copy-Item -Destination "C:/Program Files/Csound6_x64" -Recurse -Container
  # - cmd: cd "C:/Program Files/Csound6_x64"
  # - cmd: cd include
  # - cmd: mkdir csound
  # - cmd: cd csound
  # - ps: Copy-Item ../*.h .
  # - ps: Copy-Item ../*.hpp . 
  # - cmd: dir
  # - cmd: cd "C:/Program Files/Csound6_x64"
  # - cmd: dir
  # - cmd: mkdir lib 
  # - cmd: cd lib  
  # - ps: Copy-Item ../*.dll .
  # - ps: Copy-Item ../*.lib .
  # - cmd: dir
  # - cmd: pwd
  - cmd: cd c:/
  - ps: Start-FileDownload 'https://download.steinberg.net/sdk_downloads/vstsdk3611_22_10_2018_build_34.zip'
  - ps: Start-FileDownload 'http://www.steinberg.net/sdk_downloads/ASIOSDK2.3.2.zip'
  - ps: Start-FileDownload 'http://cabbageaudio.com/beta/heads.zip'
  - cmd: 7z.exe x vstsdk3611_22_10_2018_build_34.zip
  - cmd: 7z.exe x asiosdk2.3.2.zip
  - cmd: 7z.exe x heads.zip
  - cmd: mkdir SDKs  
  - cmd: dir
  - ps: Get-ChildItem -Path "C:/VST_SDK" | Copy-Item -Destination "C:/SDKs/VST_SDK" -Recurse -Container
  - ps: Get-ChildItem -Path "C:/vst2.x" | Copy-Item -Destination "C:/SDKs/VST_SDK/VST3_SDK/pluginterfaces" -Recurse -Container
  - ps: Get-ChildItem -Path "C:/ASIOSDK2.3.2" | Copy-Item -Destination "C:/SDKs/ASIOSDK2.3.2" -Recurse -Container
  
  - cmd: cd c:/SDKs/VST_SDK/VST3_SDK/pluginterfaces/
  - cmd: dir
  
  - cmd: git clone https://github.com/WeAreROLI/JUCE.git
  - cmd: cd c:/JUCE/
  - cmd: git checkout tags/5.4.1
  - cmd: cd c:/JUCE/extras/Projucer/JuceLibraryCode
  - ps: (Get-Content -Path "AppConfig.h") | ForEach-Object {$_ -Replace "#define JUCER_ENABLE_GPL_MODE 1", "#define JUCER_ENABLE_GPL_MODE 0"} | Set-Content -Path "AppConfig.h"
  - ps: (Get-Content -Path "AppConfig.h") | ForEach-Object {$_ -Replace "#define JUCE_USE_DARK_SPLASH_SCREEN 1", "#define JUCE_USE_DARK_SPLASH_SCREEN 0"} | Set-Content -Path "AppConfig.h"

branches:
  only:
    - master
    
build:
  project: c:/cabbage/Builds/VisualStudio2017/Cabbage.sln

before_build:
  - cmd: cd ../Builds/VisualStudio2017/
  - cmd: msbuild Projucer.sln /property:Platform=x64
  - cmd: cd c:/cabbage/Builds/VisualStudio2017/
  - cmd: appveyorBuildCabbage64.bat  
  - cmd: cd c:/cabbage/CsoundTestWin64 
  - cmd: msbuild CsoundTest.sln /property:Platform=x64
  - cmd: cd C:/cabbage
  - ps: Start-FileDownload 'http://cabbageaudio.com/beta/CabbageManual.zip'
  - cmd: 7z.exe x CabbageManual.zip  -oC:\cabbage\CabbageManual
  - ps: Start-FileDownload 'https://github.com/rorywalsh/CabbageRack/releases/download/v1.0/CabbageRack-0.5.0-win.zip'
  - cmd: 7z.exe x CabbageRack-0.5.0-win.zip -oC:\cabbage\Builds\VisualStudio2017\x64\CabbageRack
  - cmd: ls
  - cmd: cd c:/cabbage/Builds/VisualStudio2017/x64
  - ps: Start-FileDownload 'https://github.com/rorywalsh/csoundfmod/releases/download/v1.1/fmod_csoundL64.dll'
  - cmd: ls
  - cmd: cd c:/cabbage/Builds/VisualStudio2017

after_build:
  - cmd: set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"
  - cmd: iscc CabbageCannonicalInstaller.iss

artifacts:
  - path: Builds/VisualStudio2017/Output/Cabbage64Setup.exe
  - path: logs

deploy:
- provider: BinTray
  username: rorywalsh
  api_key:
    secure: gMAIlZljfEQMFSNZse9AY9nuelv0siT2X5N0ZTFhhKCew8NKWNHeizWlbdMeggi7
  subject: rorywalsh
  repo: Cabbage
  package: CabbageWin64
  version: beta
  publish: true
  override: true
  explode: true

  
