# Only trigger CI builds for the master branch, instead 
# of every branch. You'll automatically be configured to 
# build PRs, but you can't currently control that from the YAML directly
# For details, see https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers
trigger:
- develop

# We can run multiple jobs in parallel. For this project
# I'm running Linux, Windows, and macOS jobs. For syntac details
# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases
jobs:

# Run a build on Windows at the same time
# - job: Windows
#   pool:
#     vmImage: 'vs2017-win2016'
#   # The Windows build involves running a powershell script
#   # to execute the Cake build script
#   steps:
#   - powershell: gci env:* | sort-object name | Format-Table -AutoSize
#   - powershell: .\buildWindows.ps1
#     env:
#       COREHOST_TRACE: 0
#       DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
#       DOTNET_CLI_TELEMETRY_OPTOUT: 1


#   - task: PublishBuildArtifacts@1
#     inputs:
#       pathtoPublish: '$(Build.ArtifactStagingDirectory)'
#       artifactName: '${SYSTEM_DEFAULTWORKINGDIRECTORY}/Cabbage64Setup.exe'
  
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - bash: chmod 777 buildOSX.sh
  - bash: ./buildOSX.sh
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1